export const ADD_PERSONAL = 'ADD_PERSONAL';
export const ADD_PERSONAL_SUCCESS = 'ADD_PERSONAL_SUCCESS';
export const ADD_PERSONAL_ERROR = 'ADD_PERSONAL_ERROR';

export const EDIT_PERSONAL = 'EDIT_PERSONAL';
export const EDIT_PERSONAL_SUCCESS = 'EDIT_PERSONAL_SUCCESS';
export const EDIT_PERSONAL_ERROR = 'EDIT_PERSONAL_ERROR';

export const DELETE_PERSONAL = 'DELETE_PERSONAL';
export const DELETE_PERSONAL_SUCCESS = 'DELETE_PERSONAL_SUCCESS';
export const DELETE_PERSONAL_ERROR = 'DELETE_PERSONAL_ERROR';

export const GET_PERSONAL = 'GET_PERSONAL';
export const GET_PERSONAL_SUCCESS = 'GET_PERSONAL_SUCCESS';
export const GET_PERSONAL_ERROR = 'GET_PERSONAL_ERROR';

export const GET_PERSONALS = 'GET_PERSONALS';
export const GET_PERSONALS_SUCCESS = 'GET_PERSONALS_SUCCESS';
export const GET_PERSONALS_ERROR = 'GET_PERSONALS_ERROR';
